// 定义公共的 IPC_ACTIONS
const IPC_ACTIONS = {
  // sockes server
  START_SOCKS_SERVICE: 'START_SOCKS_SERVICE',
  SOCKS_SERVICE_OUTPUT: 'SOCKS_SERVICE_OUTPUT',
  SOCKS_SERVICE_ERROR: 'SOCKS_SERVICE_ERROR',
  SOCKS_SERVICE_STOPPED: 'SOCKS_SERVICE_STOPPED',
  STOP_SOCKS_SERVICE: 'STOP_SOCKS_SERVICE',
  SOCKS_SERVICE_STATUS: 'SOCKS_SERVICE_STATUS',
  CHECK_SOCKS_SERVICE: 'CHECK_SOCKS_SERVICE',
  GET_SOCKS_SERVICE_INFO: 'GET_SOCKS_SERVICE_INFO',
  // system
  GET_LOGS: 'GET_LOGS',
  SUBPROCESS_ERROR: 'SUBPROCESS_ERROR',
  GET_WIFI: 'GET_WIFI',
  // file
  SELECT_FILE: 'SELECT_FILE',
  GET_DIRECTORY_STRUCTURE: 'GET_DIRECTORY_STRUCTURE',
  PARSE_DOC_FILE: 'PARSE_DOC_FILE',
  CONVERT_DOC_TO_IMAGE: 'CONVERT_DOC_TO_IMAGE',
  SAVE_BASE64_IMAGE: 'SAVE_BASE64_IMAGE',
  LS_FOLDER: 'LS_FOLDER',
  LOAD_VIDEO: 'LOAD_VIDEO',
  READ_STREAM: 'READ_STREAM',
  CHECK_FOLDER_EXIST: 'CHECK_FOLDER_EXIST',
  READ_JSON: 'READ_JSON',
  SAVE_JSON: 'SAVE_JSON',
  DELETE_FILE: 'DELETE_FILE',
  // image file
  SAVE_SCREENSHOT: 'SAVE_SCREENSHOT',
  REMOVE_SCREENSHOT: 'REMOVE_SCREENSHOT',
  BATCH_CROP_IMAGE: 'BATCH_CROP_IMAGE',
  MERGE_IMAGES: 'MERGE_IMAGES',
  COMPARE_IMAGES: 'COMPARE_IMAGES',
  EXRACT_IMAGES_TEXT: 'EXRACT_IMAGES_TEXT',
  EXRACT_VIDEO_FRAME_TEXT: 'EXRACT_VIDEO_FRAME_TEXT',
  IMAGE_TO_ICONS: 'IMAGE_TO_ICONS',
  // download video from ytb
  DOWNLOAD_PAUSE: 'DOWNLOAD_PAUSE',
  DOWNLOAD_RESUME: 'DOWNLOAD_RESUME',
  DOWNLOAD_CANCEL: 'DOWNLOAD_CANCEL',
  DOWNLOAD_START: 'DOWNLOAD_START',
  DOWNLOAD_TITLE: 'DOWNLOAD_TITLE',
  DOWNLOAD_PROGRESS: 'DOWNLOAD_PROGRESS',
  DOWNLOAD_COMPLETE: 'DOWNLOAD_COMPLETE',
  DOWNLOAD_ERROR: 'DOWNLOAD_ERROR',
} as const

//  module.exports = {
//     IPC_ACTIONS
//  }
export type IPC_ACTIONS_TYPE = typeof IPC_ACTIONS

export { IPC_ACTIONS }
